### ISSUE TITLE
properties files are doubled in non-existing path

### ISSUE THREAD

**Issue by wofrank** [jutzig/jabylon#235]
**Description**
In my installation I have all properties files doubled within a non-existing folder.
The right location is product-lib/resources/* but jabylon also offers the translations in resources/*.

**Version**
* 1.1.3
* both: Windows and Linux
* using git team provider

**More details**
After adding a git project to jabylon and doing a scan, I have all properties files twice in the system:

See the structure in jabylon:
![structure_jabylon](https://cloud.githubusercontent.com/assets/11269960/6439898/e3e81298-c0d7-11e4-9207-08b54e63af5a.PNG)

So I am able to navigate to the non existing file:
```Home /workspace /MTP /master /fr /resources /level2 /level2_fr.properties /```

The following (correct) file is also available in jabylon:
```Home /workspace /MTP /master /fr /product-lib /resources /level2 /level2_fr.properties /```

The following screenshot shows the project structure in file system:
![project_structure](https://cloud.githubusercontent.com/assets/11269960/6439826/14bcde22-c0d7-11e4-86c3-be2c98a53aea.PNG)

I also get some messages on scanning the directory:
```DEBUG   o.j.p.i.PropertyFileDescriptorImpl Tried to load non-existing property file. Path: /$WORKSPACE_PATH/MTP/master/resources/level2/2level2_fr.properties```

**Comment by jutzig** [comment]
I think this problem was solved in this commit:
https://github.com/jutzig/jabylon/commit/4f6d82011ad97733f6947e810e01aa27b249d653
I did not release this version yet but if you want I can produce a snapshot build that includes the fix so you can confirm if this solves the issue for you

**Comment by wofrank** [comment]
Thanks for the fast feedback.
A snapshot would be nice, if there is not an easy workaround.

**Comment by svogt** [comment]
@wofrank Latest snapshot builds are available here: http://jenkins-jabylon.rhcloud.com/job/jabylon/lastSuccessfulBuild/artifact/releng/standalone/target/jabylon-standalone.zip

**Comment by jutzig** [comment]
This won't help. The fix is not in master but in a topic branch. I'll either post a link to a custom build or merge the changes to master...

**Comment by jutzig** [comment]
I merged the changes back to master so the snapshot build now contains this fix and several others.
http://jenkins-jabylon.rhcloud.com/job/jabylon/lastSuccessfulBuild/artifact/releng/standalone/target/jabylon-standalone.zip
Please let me know if this solves the issue for you. If so, I will create a new release this week.

**Comment by wofrank** [comment]
Great. Solves the Problem. Many thanks.
It solves also an issue that it was not possible to create a terminology project. I guess it was the same issue, as the exception was in fixed calulate... method.

**Comment by jutzig** [comment]
Great, then I will create a new release
