### ISSUE TITLE
Is it possible to add new key via Jabilon UI

### ISSUE THREAD

**Issue by demon101** [jutzig/jabylon#254]
I can't find, how I can add new translation (new keys) via Jabilon.
Is it possible?

**Comment by svogt** [comment]
Hi,

this is not possible, as it's pretty pointless to add a new key when the software isn't using the key. The developer who adds a new localizable String in the software needs to create the key in the "master" language. 

Greetings
.sascha

PS: For further questions please use the Google group at https://groups.google.com/forum/#!forum/jabylon and not the Github issue tracker.
