### ISSUE TITLE
multiline support on strings file

### ISSUE THREAD

**Issue by ramarro123** [jutzig/jabylon#270]
Hello,

i am having trouble on multiline text on .strings file format.

if i try to localize
"test\ntest" = "";
and i add something like
a <enter> b <enter> c

i got
"test\ntest" = "a\r\nb\r\nc";

that is tecnically speaking correct, but it's could be a problem for translation purpose

standing to that:
http://www.cs.toronto.edu/~krueger/csc209h/tut/line-endings.html
new line it's differnet based on OS, but my jabylon run on linux, so the expected new line should be '\n'
probably since java it's at an upper level, it doesn't mean anything.

do you have an idea on how we can fix that?

**Comment by jutzig** [comment]
In the end this comes down to the target format. When using java property files, both types of line feed are valid, so I don't see an issue here.
What sort of problem are you expecting?

**Comment by ramarro123** [comment]
i use this string to draw into an html canvas using pixi as a renderer engine.

the text "a\r\ntest" get rendered with 2 lines like
a
<empty>
<empty>
test


the expected result should be

a
<empty>
test


i can of course do some fixing on the app, so it's not a big deal, just want to make you know of what i found :)

**Comment by jutzig** [comment]
It's not that Jabylon takes your linefeed and converts it to \r\n, I don't think that is a choice we can make for the user.
Instead it takes what you enter in the textfield and encodes it in the properties file.
In your case, I assume you're running on Windows, so when you hit enter, you end up with a \r\n linefeed and that's what gets written to the file

**Comment by ramarro123** [comment]
i am actually on unix, but probably \r\n it's a standard things on textarea.

anyway i will deal with it on client side, it's not a big deal
